language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8

services:
  - couchdb
  
before_script:
  - curl -X PUT localhost:5984/metamodel_test_database

after_success:
  - mvn test
 
notifications:
  email: false